CNN:
  input_dim: 769
  seq_length: 7
  hidden_dim: 12
  n_layers: 3
  output_dim: 5
  kernel_size: 3
  dropout: 0.3
Loss:
  loss_type: focal
  beta: 0.95
  gamma: 2.0
Optim:
  Schedule:
    args:
      lambda:
        val: 10
      multiplicative:
        val: 10
      step:
        gamma: 0.95
        step_size: 10
    name: step
    warm_up: 300
  args:
    adam:
      betas:
      - 0.9
      - 0.9999
      eps: 1.0e-06
    rmsprop:
      eps: 1.0e-08
    sgd:
      momentum: 0.9
  name: adam
accumulate_grad_batches: 1
amp_level: O1
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 64
benchmark: true
check_val_every_n_epoch: 1
checkpoint_callback: true
data_root: /home/tarask/Documents/Datasets/SaGa/Processed/feat/R_Semantics/Plain/
data_feat: R.G.Right Semantic
dropout: 0.2
default_root_dir: null
deterministic: true
distributed_backend: null
early_stop_callback: false
fast_dev_run: false
gradient_clip_val: 20
log_gpu_memory: null
log_save_interval: 80
log_root: results/gesture_flow/log/
logger: true
lr: 1.0e-04
max_epochs: 15
max_steps: null
min_epochs: 1
min_steps: null
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 1
num_tpu_cores: null
optuna: true
overfit_pct: 0.0
precision: 32
print_nan_grads: false
process_position: 0
profiler: null
progress_bar_callback: true
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
row_log_interval: 10
terminate_on_nan: false
test_percent_check: 1.0
track_grad_norm: -1
train_percent_check: 1.0
truncated_bptt_steps: null
val_check_interval: 1.0
val_gest_dir: ./results/gesture_flow/val_res
val_percent_check: 0.2
weights_save_path: null
weights_summary: top
comet_logger:
  api_key: DVWPz8OdEU7HGvsUjlJhh5Q5p
  project_name: prop_predict
