Glow:
  K: 4
  L: 1
  LU_decomposed: true
  actnorm_scale: 1.0
  flow_coupling: affine
  flow_permutation: shuffle
  hidden_channels: 64
  rnn_type: gru
  scale_eps: 0.0001
  distr_dim: 45
  speech_cond_dim: 64
  conv_seq_len: 3
  CNN:
    numb_layers: 4
    kernel_size: 3
Infer:
  temp: 0.8
  seq_len: 120
Optim:
  Schedule:
    args:
      lambda:
        val: 10
      multiplicative:
        val: 10
      step:
        gamma: 0.7
        step_size: 3
    name: step
    warm_up: 500
  args:
    adam:
      betas:
      - 0.9
      - 0.9999
      eps: 1.0e-06
    rmsprop:
      eps: 1.0e-08
    sgd:
      momentum: 0.9
  name: adam
Train:
  seq_len: 70
Cond:
  Speech:
    dim: 837
    fr_enc_dim: 16
    total_enc_dim: 64
    prev_context: 5
    future_context: 10
  Autoregression:
    history_length: 0
Validation:
  check_invertion: true
  inference: true
  render: false
  scale_logging: true
  seq_len: 230
  teacher_forced_inference: true
accumulate_grad_batches: 1
amp_level: O1
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 64
benchmark: true
check_val_every_n_epoch: 1
checkpoint_callback: true
data_root: /home/taras/Documents/storage/Irish/GestureFlow_hdf5
dropout: 0.2
default_root_dir: null
deterministic: true
distributed_backend: null
early_stop_callback: false
fast_dev_run: false
gradient_clip_val: 20
log_gpu_memory: null
log_save_interval: 100
log_root: results/gesture_flow/log/
logger: true
lr: 1.0e-03
max_epochs: 2
max_steps: null
min_epochs: 1
min_steps: null
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 1
num_tpu_cores: null
optuna: true
overfit_pct: 0.0
precision: 32
print_nan_grads: false
process_position: 0
profiler: null
progress_bar_callback: true
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
row_log_interval: 10
terminate_on_nan: false
test_percent_check: 1.0
track_grad_norm: -1
train_percent_check: 1.0
truncated_bptt_steps: null
val_check_interval: 1.0
val_gest_dir: ./results/gesture_flow/val_res
val_percent_check: 0.1
weights_save_path: null
weights_summary: top
comet_logger:
  api_key: DVWPz8OdEU7HGvsUjlJhh5Q5p
  project_name: development
